spring.application.name=NewsWebsite

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

kids.rss.url=https://www.thehindu.com/children/?service=rss

adult.rss.hindu=https://www.thehindu.com/news/national/?service=rss
adult.rss.indianexpress=https://indianexpress.com/section/india/feed/
adult.rss.business=https://www.thehindu.com/business/?service=rss

admin.password=${ADMIN_PASSWORD}

groq.api.key=${GROQ_API_KEY}