spring.application.name=NewsWebsite
spring.datasource.url=jdbc:mysql://localhost:3306/newswebsite
spring.datasource.username=root
spring.datasource.password=Lisha@15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9999

kids.rss.url=https://www.thehindu.com/children/?service=rss

adult.rss.hindu=https://www.thehindu.com/news/national/?service=rss
adult.rss.indianexpress=https://indianexpress.com/section/india/feed/
adult.rss.business=https://www.thehindu.com/business/?service=rss

admin.password=admin123

# Groq configuration using OpenAI-compatible API
groq.api.key=${groq.api.key:}
